name: Flat
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 #install the python needed
      - name: execute py script
        env:
          MS_TOKEN: ${{ secrets.MS_TOKEN }}
        run: |
          python3.9 -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          pip install -r requirements.txt
          python -m playwright install
          patch venv/lib/python3.9/site-packages/TikTokApi/tiktok.py -i tiktok.py.patch
          python postprocessing.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Latest TikTok RSS"
          git push
